/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
-/

/-
This module formalizes the instability of the Randomized Sketch-and-Precondition algorithm using a probabilistic argument.
It defines the space of all 2x2 SRHT matrices and a uniform probability measure on them.
It constructs a specific "bad" matrix A and proves that for any SRHT matrix S drawn from this distribution, the condition number of the preconditioned system is large.
Consequently, the probability of instability is 1, demonstrating that the algorithm is not backward stable.
-/

import Mathlib

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise




open Matrix

def hadamard (k : ℕ) : Matrix (Fin (2^k)) (Fin (2^k)) ℝ :=
  match k with
  | 0 => !![1]
  | k+1 =>
    let H := hadamard k
    let H2 := Matrix.fromBlocks H H H (-H)
    let e : Fin (2^k) ⊕ Fin (2^k) ≃ Fin (2^(k+1)) :=
      finSumFinEquiv.trans (finCongr (by ring))
    Matrix.reindex e e H2

def is_sampling_matrix {m s : ℕ} (P : Matrix (Fin s) (Fin m) ℝ) : Prop :=
  ∃ f : Fin s ↪ Fin m, P = of (fun i j => if j = f i then 1 else 0)

def is_sign_matrix {m : ℕ} (D : Matrix (Fin m) (Fin m) ℝ) : Prop :=
  IsDiag D ∧ ∀ i, |D i i| = 1

def is_SRHT {k s : ℕ} (S : Matrix (Fin s) (Fin (2^k)) ℝ) : Prop :=
  ∃ (P : Matrix (Fin s) (Fin (2^k)) ℝ) (D : Matrix (Fin (2^k)) (Fin (2^k)) ℝ),
    is_sampling_matrix P ∧ is_sign_matrix D ∧
    S = (Real.sqrt ((2^k : ℝ) / s)) • (P * hadamard k * D)

noncomputable def Matrix.conditionNumber {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) : ℝ :=
  if h : 0 < n then
    let M := Aᵀ * A
    let eig := (isHermitian_transpose_mul_self A).eigenvalues
    let s : Finset ℝ := (Finset.univ : Finset (Fin n)).image eig
    let max_eig := s.max' (by
    apply Finset.Nonempty.image; exact Finset.univ_nonempty_iff.mpr ⟨⟨0, h⟩⟩)
    let min_eig := s.min' (by
    all_goals generalize_proofs at *;
    apply ‹s.Nonempty›)
    Real.sqrt (max_eig / min_eig)
  else 0

def is_upper_triangular {n : ℕ} (R : Matrix (Fin n) (Fin n) ℝ) : Prop :=
  ∀ i j, j < i → R i j = 0

def is_QR {s n : ℕ} (A : Matrix (Fin s) (Fin n) ℝ) (Q : Matrix (Fin s) (Fin n) ℝ) (R : Matrix (Fin n) (Fin n) ℝ) : Prop :=
  A = Q * R ∧ Qᵀ * Q = 1 ∧ is_upper_triangular R

noncomputable def mat_norm {m n : ℕ} (A : Matrix (Fin m) (Fin n) ℝ) : ℝ :=
  if h : 0 < n then
    let eig := (isHermitian_transpose_mul_self A).eigenvalues
    let s : Finset ℝ := (Finset.univ : Finset (Fin n)).image eig
    Real.sqrt (s.max' (by apply Finset.Nonempty.image; exact Finset.univ_nonempty_iff.mpr ⟨⟨0, h⟩⟩))
  else 0

lemma hadamard_zero : hadamard 0 = !![1] := by
  rfl

lemma hadamard_one : hadamard 1 = !![1, 1; 1, -1] := by
  ext i j; simp [Fin.sum_univ_succ, Fin.sum_univ_zero];
  fin_cases i <;> fin_cases j <;> rfl

open Matrix
open scoped BigOperators
open scoped Real

def all_sampling_matrices (n s : ℕ) : Finset (Matrix (Fin s) (Fin n) ℝ) :=
  (Finset.univ : Finset (Fin s ↪ Fin n)).image (fun f => Matrix.of (fun i j => if j = f i then 1 else 0))

def all_sign_matrices (n : ℕ) : Finset (Matrix (Fin n) (Fin n) ℝ) :=
  (Finset.univ : Finset (Fin n → Bool)).image (fun σ => Matrix.diagonal (fun i => if σ i then 1 else -1))

def all_SRHT_matrices (k s : ℕ) : Finset (Matrix (Fin s) (Fin (2^k)) ℝ) :=
  let n := 2^k
  let P_set := all_sampling_matrices n s
  let D_set := all_sign_matrices n
  let H := hadamard k
  let scale := Real.sqrt ((n : ℝ) / s)
  Finset.image₂ (fun P D => scale • (P * H * D)) P_set D_set

lemma all_SRHT_matrices_nonempty_1_2 : (all_SRHT_matrices 1 2).Nonempty := by
  -- The set of all SRHT matrices for k=1 and s=2 is nonempty because there are multiple valid combinations of sampling, Hadamard, and sign matrices.
  simp [all_SRHT_matrices];
  -- For the sampling matrices, the identity function is a valid embedding, and for the sign matrices, the matrix with all 1s is valid.
  simp [all_sampling_matrices, all_sign_matrices];
  -- The universal set is nonempty because it contains at least one element.
  simp [Finset.Nonempty];
  -- The identity function is an embedding from Fin 2 to Fin 2.
  use fun x => x;
  -- The identity function is injective by definition.
  simp [Function.Injective]

noncomputable def random_SRHT_1_2 : PMF (Matrix (Fin 2) (Fin 2) ℝ) :=
  PMF.uniformOfFinset (all_SRHT_matrices 1 2) all_SRHT_matrices_nonempty_1_2

noncomputable def bad_A (ε : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  (1/2 : ℝ) • (hadamard 1 * !![1, 0; 0, ε])

noncomputable def bad_E (ε K : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  let η := ε / (2 * (|K| + 1))
  !![0, 0; 0, η - ε]

noncomputable def bad_Q : Matrix (Fin 2) (Fin 2) ℝ := 1

noncomputable def bad_R (ε K : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  let η := ε / (2 * (|K| + 1))
  !![1, 0; 0, η]

def is_unstable (S : Matrix (Fin 2) (Fin 2) ℝ) (A : Matrix (Fin 2) (Fin 2) ℝ) (ε K : ℝ) : Prop :=
  ∃ (E : Matrix (Fin 2) (Fin 2) ℝ) (Q : Matrix (Fin 2) (Fin 2) ℝ) (R : Matrix (Fin 2) (Fin 2) ℝ),
    mat_norm E ≤ ε * mat_norm (S * A) ∧
    is_QR (S * A + E) Q R ∧
    R.det ≠ 0 ∧
    Matrix.conditionNumber (A * R⁻¹) > K

instance : MeasurableSpace (Matrix (Fin 2) (Fin 2) ℝ) :=
  MeasurableSpace.pi

lemma SRHT_structure (S : Matrix (Fin 2) (Fin 2) ℝ) (hS : S ∈ all_SRHT_matrices 1 2) :
  ∃ (P : Matrix (Fin 2) (Fin 2) ℝ) (D : Matrix (Fin 2) (Fin 2) ℝ),
    (P = 1 ∨ P = !![0, 1; 1, 0]) ∧
    (D = !![1, 0; 0, 1] ∨ D = !![-1, 0; 0, 1] ∨ D = !![1, 0; 0, -1] ∨ D = !![-1, 0; 0, -1]) ∧
    S = P * hadamard 1 * D := by
      -- By definition of `all_SRHT_matrices`, we know that every element in this set is of the form `P * hadamard 1 * D` for some `P` and `D`.
      obtain ⟨P, D, hP, hD, hS⟩ : ∃ P D : Matrix (Fin 2) (Fin 2) ℝ, P ∈ all_sampling_matrices 2 2 ∧ D ∈ all_sign_matrices 2 ∧ S = P * hadamard 1 * D := by
        unfold all_SRHT_matrices at hS; aesop;
      -- By definition of `all_sampling_matrices` and `all_sign_matrices`, we know that `P` must be one of the permutation matrices and `D` must be one of the diagonal matrices with entries ±1.
      have hP_cases : P = 1 ∨ P = !![0, 1; 1, 0] := by
        -- Since $P$ is a permutation matrix, it must be either the identity matrix or the permutation matrix that swaps the two rows.
        have hP_cases : P = 1 ∨ P = !![0, 1; 1, 0] := by
          have h_perm : ∃ f : Fin 2 ≃ Fin 2, P = Matrix.of (fun i j => if j = f i then 1 else 0) := by
            unfold all_sampling_matrices at hP; aesop;
            exact ⟨ Equiv.ofBijective w (by
            exact ⟨ w.injective, Finite.injective_iff_surjective.mp w.injective ⟩), rfl ⟩
            skip
          rcases h_perm with ⟨ f, rfl ⟩ ; fin_cases f <;> norm_num [ ← Matrix.ext_iff, Fin.forall_fin_two ] ;
          exact funext fun i => funext fun j => by fin_cases i <;> fin_cases j <;> rfl;
        exact hP_cases
      have hD_cases : D = !![1, 0; 0, 1] ∨ D = !![-1, 0; 0, 1] ∨ D = !![1, 0; 0, -1] ∨ D = !![-1, 0; 0, -1] := by
        -- Since $D$ is a sign matrix, it must be diagonal with entries $\pm 1$.
        have hD_diag : D = Matrix.diagonal (fun i => if i = 0 then if D 0 0 = 1 then 1 else -1 else if D 1 1 = 1 then 1 else -1) := by
          unfold all_sign_matrices at hD; aesop;
        rcases eq_or_ne ( D 0 0 ) 1 with ha | ha <;> rcases eq_or_ne ( D 1 1 ) 1 with hb | hb <;> norm_num [ ha, hb ] at hD_diag ⊢;
        · exact Or.inl <| hD_diag.trans <| by ext i j; fin_cases i <;> fin_cases j <;> rfl;
        · exact Or.inr <| Or.inr <| Or.inl <| hD_diag.trans <| by ext i j; fin_cases i <;> fin_cases j <;> rfl;
        · exact Or.inr <| Or.inl <| hD_diag.trans <| by ext i j; fin_cases i <;> fin_cases j <;> rfl;
        · exact Or.inr <| Or.inr <| Or.inr <| hD_diag.trans <| by ext i j; fin_cases i <;> fin_cases j <;> norm_num;
      rcases hP_cases with ( rfl | rfl ) <;> rcases hD_cases with ( rfl | rfl | rfl | rfl ) <;> norm_num [ hS ]

def is_perm_matrix (P : Matrix (Fin 2) (Fin 2) ℝ) : Prop :=
  P = 1 ∨ P = !![0, 1; 1, 0]

def is_sign_matrix_2x2 (D : Matrix (Fin 2) (Fin 2) ℝ) : Prop :=
  D = !![1, 0; 0, 1] ∨ D = !![-1, 0; 0, 1] ∨ D = !![1, 0; 0, -1] ∨ D = !![-1, 0; 0, -1]

lemma SRHT_mul_bad_A_structure (S : Matrix (Fin 2) (Fin 2) ℝ) (hS : S ∈ all_SRHT_matrices 1 2) (ε : ℝ) :
  ∃ (P : Matrix (Fin 2) (Fin 2) ℝ) (D : Matrix (Fin 2) (Fin 2) ℝ),
    is_perm_matrix P ∧ is_sign_matrix_2x2 D ∧
    S * bad_A ε = P * D * !![1, 0; 0, ε] := by
      obtain ⟨ P, D, hP, hD, rfl ⟩ := SRHT_structure S hS;
      -- By definition of $hadamard 1$, we know that $hadamard 1 = !![1, 1; 1, -1]$.
      have h_hadamard_1 : hadamard 1 = !![1, 1; 1, -1] := by
        exact?;
      unfold bad_A;
      rcases hP with ( rfl | rfl ) <;> rcases hD with ( rfl | rfl | rfl | rfl ) <;> norm_num [ h_hadamard_1 ];
      all_goals norm_num [ is_perm_matrix, is_sign_matrix_2x2 ];
      all_goals ring_nf; norm_num;

lemma hadamard_conjugation (D0 : Matrix (Fin 2) (Fin 2) ℝ) (hD0 : is_sign_matrix_2x2 D0) :
  ∃ P1 D1, is_perm_matrix P1 ∧ is_sign_matrix_2x2 D1 ∧
  _root_.hadamard 1 * D0 * _root_.hadamard 1 = (2 : ℝ) • (P1 * D1) := by
    rcases hD0 with ( rfl | rfl | rfl | rfl ) <;> norm_num [ hadamard_one ] at *;
    · unfold is_perm_matrix is_sign_matrix_2x2; norm_num;
    · use !![0, 1; 1, 0];
      -- Let's choose the sign matrix $D = !![-1, 0; 0, -1]$.
      use by
        -- The matrix !![0, 1; 1, 0] is a permutation matrix because it swaps the rows.
        simp [is_perm_matrix], !![-1, 0; 0, -1];
      aesop;
      exact Or.inr <| Or.inr <| Or.inr rfl;
    · -- Let's choose P1 as the permutation matrix that swaps the rows and D1 as the identity matrix.
      use !![0, 1; 1, 0], by
        -- The matrix !![0, 1; 1, 0] is a permutation matrix because it swaps the rows.
        simp [is_perm_matrix], !![1, 0; 0, 1], by
        exact Or.inl rfl;
      ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ two_mul ];
    · -- Let's choose P1 as the identity matrix and x as !![-1, 0; 0, -1].
      use 1, by
        exact Or.inl rfl, !![-1, 0; 0, -1], by
        exact Or.inr <| Or.inr <| Or.inr rfl
      generalize_proofs at *;
      ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ two_smul ]

lemma is_perm_matrix_unitary (P : Matrix (Fin 2) (Fin 2) ℝ) (hP : is_perm_matrix P) :
  Pᵀ * P = 1 := by
    -- Since $P$ is a permutation matrix, it is orthogonal, meaning $P^T P = I$.
    cases' hP with hP_id hP_swap
    aesop
    first | (generalize_proofs at *; (
    -- By definition of matrix multiplication, we can compute each element of the product.
    ext i j; fin_cases i <;> fin_cases j <;> norm_num [ hP_swap, Matrix.mul_apply ])) | skip

lemma is_sign_matrix_unitary (D : Matrix (Fin 2) (Fin 2) ℝ) (hD : is_sign_matrix_2x2 D) :
  Dᵀ * D = 1 := by
    -- Since D is a sign matrix, it is either the identity matrix or a diagonal matrix with entries ±1.
    cases' hD with hD_id hD_diag;
    · aesop;
      -- By definition of matrix multiplication, we can compute each element of the product.
      ext i j; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply ];
    · rcases hD_diag with ( rfl | rfl | rfl ) <;> ext i j <;> fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply ]

lemma perm_sign_unitary (P D : Matrix (Fin 2) (Fin 2) ℝ) (hP : is_perm_matrix P) (hD : is_sign_matrix_2x2 D) :
  (P * D)ᵀ * (P * D) = 1 := by
    rcases hP with ( rfl | rfl ) <;> rcases hD with ( rfl | rfl | rfl | rfl ) <;> norm_num [ Matrix.mul_assoc ];
    all_goals ext i j; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, Fin.sum_univ_succ ] ;

lemma mat_norm_unitary_mul (U A : Matrix (Fin 2) (Fin 2) ℝ) (hU : Uᵀ * U = 1) :
  mat_norm (U * A) = mat_norm A := by
    -- Since $U$ is orthogonal, we have $(U * A)^T * (U * A) = A^T * U^T * U * A = A^T * A$.
    have h_ortho : (U * A).transpose * (U * A) = A.transpose * A := by
      -- Since $U$ is orthogonal, we have $U^T U = I$, so $(U * A)^T * (U * A) = A^T * U^T * U * A = A^T * A$.
      simp [Matrix.mul_assoc, hU];
      simp +decide [ ← Matrix.mul_assoc, hU ];
    -- Since the eigenvalues of $(U * A)^T * (U * A)$ are the same as those of $A^T * A$, their maximum eigenvalues are equal.
    have h_eigenvalues : (isHermitian_transpose_mul_self (U * A)).eigenvalues = (isHermitian_transpose_mul_self A).eigenvalues := by
      congr! 1;
    unfold mat_norm; aesop;

lemma sqrt_max (x y : ℝ) (hx : 0 ≤ x) (hy : 0 ≤ y) : Real.sqrt (max x y) = max (Real.sqrt x) (Real.sqrt y) := by
  cases le_total x y <;> simp +decide [ *, Real.sqrt_le_sqrt ]

open Matrix Polynomial

lemma charpoly_diagonal_2x2 (a b : ℝ) :
  (!![a, 0; 0, b] : Matrix (Fin 2) (Fin 2) ℝ).charpoly = (X - C a) * (X - C b) := by
  rw [Matrix.charpoly_fin_two]
  simp
  ring

#print Matrix.IsHermitian
#check Matrix.IsHermitian.eigenvalues

open Matrix Polynomial

lemma eigenvalues_diagonal_2x2 (a b : ℝ) (hA : IsHermitian !![a, 0; 0, b]) :
  (Finset.univ.image hA.eigenvalues).toSet = {a, b} := by
    have h_eigenvalues : hA.eigenvalues 0 = a ∧ hA.eigenvalues 1 = b ∨ hA.eigenvalues 0 = b ∧ hA.eigenvalues 1 = a := by
      have := hA.det_eq_prod_eigenvalues; simp_all +decide [ Matrix.det_fin_two ] ;
      have h_eigenvalues : hA.eigenvalues 0 + hA.eigenvalues 1 = a + b := by
        have := hA.trace_eq_sum_eigenvalues; simp_all +decide [ Matrix.trace ] ;
      generalize_proofs at *; (
      grind)
    generalize_proofs at *; (
    ext x; aesop;)

lemma pair_eq_of_sum_prod (x y a b : ℝ) (h_sum : x + y = a + b) (h_prod : x * y = a * b) :
  ({x, y} : Set ℝ) = {a, b} := by
    grind

open Matrix

lemma mat_norm_diagonal_two (a b : ℝ) : mat_norm !![a, 0; 0, b] = max |a| |b| := by
  unfold mat_norm;
  aesop
  generalize_proofs at *;
  -- The eigenvalues of $A^T A$ are $a^2$ and $b^2$, so the maximum eigenvalue is $\max(a^2, b^2)$.
  have h_eigenvalues : (Finset.univ.image (Matrix.IsHermitian.eigenvalues (show IsHermitian (Matrix.of ![![a, 0], ![0, b]]ᵀ * Matrix.of ![![a, 0], ![0, b]]) from by
                                                                            aesop))).toSet = {a^2, b^2} := by
                                                                            -- Apply the lemma that states the eigenvalues of a diagonal matrix are the diagonal entries.
                                                                            have h_eigenvalues : (Finset.univ.image (Matrix.IsHermitian.eigenvalues (show IsHermitian (Matrix.of ![![a^2, 0], ![0, b^2]]) from by
                                                                                                                                                      ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ sq ]))).toSet = {a^2, b^2} := by
                                                                                                                                                      all_goals generalize_proofs at *;
                                                                                                                                                      convert eigenvalues_diagonal_2x2 ( a^2 ) ( b^2 ) ‹_› using 1
                                                                            generalize_proofs at *;
                                                                            convert h_eigenvalues using 1
                                                                            generalize_proofs at *;
                                                                            congr! 3
                                                                            generalize_proofs at *;
                                                                            ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ sq, Matrix.mul_apply ]
  generalize_proofs at *;
  -- Since the eigenvalues are $a^2$ and $b^2$, the maximum eigenvalue is $\max(a^2, b^2)$.
  have h_max_eigenvalue : (Finset.image (Matrix.IsHermitian.eigenvalues (show IsHermitian (Matrix.of ![![a, 0], ![0, b]]ᵀ * Matrix.of ![![a, 0], ![0, b]]) from by
                                                                          assumption)) Finset.univ).max' (by
                                                                          exact?) = max (a^2) (b^2) := by
                                                                          refine' le_antisymm _ _ <;> norm_num [ Finset.max' ] at * <;> aesop
                                                                          all_goals generalize_proofs at *;
                                                                          · rw [ Set.range_eq_iff ] at h_eigenvalues ; aesop
                                                                            all_goals generalize_proofs at *;
                                                                            · exact le_total _ _;
                                                                            · exact le_total _ _;
                                                                          · rw [ Set.range_eq_iff ] at h_eigenvalues ; aesop
                                                                            generalize_proofs at *;
                                                                            · exact le_total _ _;
                                                                            · exact le_total _ _
  generalize_proofs at *;
  -- Substitute h_max_eigenvalue into the goal.
  rw [h_max_eigenvalue];
  rw [ Real.sqrt_eq_iff_mul_self_eq ] <;> norm_num [ sq_le_sq ];
  · cases max_cases ( |a| ) ( |b| ) <;> cases max_cases ( a ^ 2 ) ( b ^ 2 ) <;> cases abs_cases a <;> cases abs_cases b <;> nlinarith;
  · exact Or.inl ( sq_nonneg a )

open Matrix

lemma bad_gram_matrix (ε K : ℝ) (hε : 0 < ε) :
  let A := bad_A ε
  let R := bad_R ε K
  (A * R⁻¹)ᵀ * (A * R⁻¹) = !![1/2, 0; 0, 2 * (|K| + 1)^2] := by
    -- Let's compute the matrix (A * R⁻¹)ᵀ * (A * R⁻¹) explicitly.
    have hA_R_inv : (bad_A ε * (bad_R ε K)⁻¹) = !![1 / 2, (|K| + 1); 1 / 2, -( |K| + 1)] := by
      unfold bad_A bad_R;
      -- Let's compute the product step by step.
      have h_prod : (1 / 2 : ℝ) • (hadamard 1 * !![1, 0; 0, ε]) * !![1, 0; 0, 2 * (|K| + 1) / ε] = !![1 / 2, |K| + 1; 1 / 2, -( |K| + 1)] := by
        ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply, hadamard_one ] <;> ring_nf <;> norm_num [ hε.ne' ] ;
        · nlinarith [ mul_inv_cancel_left₀ hε.ne' |K| ];
        · -- Since ε is positive, we can simplify the expression by canceling out ε and ε⁻¹.
          field_simp [hε.ne'];
          ring;
      convert h_prod using 2 ; norm_num [ Matrix.inv_def ];
      -- By simplifying, we can see that the expression indeed equals 1.
      field_simp [mul_comm, mul_assoc, mul_left_comm];
    -- Substitute hA_R_inv into the expression and compute the product.
    simp [hA_R_inv];
    ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply ] <;> ring

open Matrix

lemma condition_number_calc (ε K : ℝ) (hε : 0 < ε) :
  let A := bad_A ε
  let R := bad_R ε K
  Matrix.conditionNumber (A * R⁻¹) = 2 * (|K| + 1) := by
    -- The eigenvalues of the Gram matrix are 1/2 and 2 * (|K| + 1)^2.
    have h_eigenvalues : let A := bad_A ε; let R := bad_R ε K; (Finset.univ.image (isHermitian_transpose_mul_self (A * R⁻¹)).eigenvalues).toSet = {1/2, 2 * (|K| + 1)^2} := by
      -- Apply the bad_gram_matrix lemma to get the diagonal matrix.
      have h_diag : let A := bad_A ε; let R := bad_R ε K; (A * R⁻¹)ᵀ * (A * R⁻¹) = !![1/2, 0; 0, 2 * (|K| + 1)^2] := by
        exact?;
      -- Apply the eigenvalues_diagonal_2x2 lemma to the diagonal matrix.
      have h_eigenvalues_diag : let A := bad_A ε; let R := bad_R ε K; (Finset.univ.image (isHermitian_transpose_mul_self (A * R⁻¹)).eigenvalues).toSet = {1/2, 2 * (|K| + 1)^2} := by
        have h_herm : IsHermitian (let A := bad_A ε; let R := bad_R ε K; (A * R⁻¹)ᵀ * (A * R⁻¹)) := by
          simp +decide [ Matrix.IsHermitian, Matrix.mul_assoc ]
        convert eigenvalues_diagonal_2x2 _ _ _ using 4;
        · aesop;
        · exact h_diag ▸ h_herm;
      convert h_eigenvalues_diag using 1;
    unfold Matrix.conditionNumber; aesop;
    -- Substitute the eigenvalues into the ratio and simplify.
    have h_ratio : (Finset.image (isHermitian_transpose_mul_self (A * R⁻¹)).eigenvalues Finset.univ).max' (by
    exact ⟨ _, Finset.mem_image_of_mem _ ( Finset.mem_univ 0 ) ⟩) = 2 * (|K| + 1)^2 ∧ (Finset.image (isHermitian_transpose_mul_self (A * R⁻¹)).eigenvalues Finset.univ).min' (by
    exact ⟨ _, Finset.mem_image_of_mem _ ( Finset.mem_univ 0 ) ⟩) = 1 / 2 := by
      -- Since the image of the eigenvalues is exactly {1/2, 2*(|K|+1)^2}, we can directly conclude the max and min.
      have h_image : Finset.image (isHermitian_transpose_mul_self (A * R⁻¹)).eigenvalues Finset.univ = {1 / 2, 2 * (|K| + 1) ^ 2} := by
        simp_all +decide [ Finset.ext_iff, Set.ext_iff ];
      -- Since the set {1/2, 2*(|K|+1)^2} has exactly two elements, the maximum is the larger one and the minimum is the smaller one.
      simp [h_image, Finset.max', Finset.min'];
      norm_num; nlinarith only [ abs_nonneg K ]
    generalize_proofs at *;
    aesop;
    rw [ Real.sqrt_sq ( by positivity ) ] ; ring ; norm_num ; ring;

lemma max_pair_finset (a b : ℝ) (s : Finset ℝ) (h : s.toSet = {a, b}) (h_nonempty : s.Nonempty) :
  s.max' h_nonempty = max a b := by
  apply le_antisymm
  · apply Finset.max'_le
    intro x hx
    rw [←Finset.mem_coe] at hx
    change _ ∈ s.toSet at hx
    rw [h] at hx
    simp at hx
    rcases hx with rfl | rfl <;> simp
  · rw [max_le_iff]
    constructor
    · apply Finset.le_max'
      rw [←Finset.mem_coe]
      change _ ∈ s.toSet
      rw [h]
      simp
    · apply Finset.le_max'
      rw [←Finset.mem_coe]
      change _ ∈ s.toSet
      rw [h]
      simp

open Matrix

lemma condition_number_calc_v2 (ε K : ℝ) (hε : 0 < ε) :
  let A := bad_A ε
  let R := bad_R ε K
  Matrix.conditionNumber (A * R⁻¹) = 2 * (|K| + 1) := by
    -- Apply the lemma that states the condition number of the bad matrix is 2*(|K| + 1) to conclude the proof.
    apply condition_number_calc ε K hε

lemma min_pair_finset (a b : ℝ) (s : Finset ℝ) (h : s.toSet = {a, b}) (h_nonempty : s.Nonempty) :
  s.min' h_nonempty = min a b := by
  apply le_antisymm
  · rw [le_min_iff]
    constructor
    · apply Finset.min'_le
      rw [←Finset.mem_coe]
      change _ ∈ s.toSet
      rw [h]
      simp
    · apply Finset.min'_le
      rw [←Finset.mem_coe]
      change _ ∈ s.toSet
      rw [h]
      simp
  · apply Finset.le_min'
    intro x hx
    rw [←Finset.mem_coe] at hx
    change _ ∈ s.toSet at hx
    rw [h] at hx
    simp at hx
    rcases hx with rfl | rfl <;> simp

lemma instability_for_all_SRHT (ε K : ℝ) (hε : 0 < ε) (S : Matrix (Fin 2) (Fin 2) ℝ) (hS : S ∈ all_SRHT_matrices 1 2) :
  is_unstable S (bad_A ε) ε K := by
    revert hS S;
    -- By definition of $bad\_A$ and $bad\_R$, we know that $S * bad\_A ε$ and $(bad\_A ε) * (bad\_R ε K)⁻¹$ have the required properties.
    intro S hS
    obtain ⟨P, D, hP, hD, hS_eq⟩ := SRHT_mul_bad_A_structure S hS ε;
    -- Let $E = P * D * !![0, 0; 0, η - ε]$.
    set E : Matrix (Fin 2) (Fin 2) ℝ := P * D * !![0, 0; 0, ε / (2 * (|K| + 1)) - ε];
    refine' ⟨ E, P * D, bad_R ε K, _, _, _, _ ⟩ <;> aesop;
    · -- Since $P * D$ is unitary, we have $\|P * D * !![0, 0; 0, η - ε]\| = \|!![0, 0; 0, η - ε]\|$ and $\|P * D * !![1, 0; 0, ε]\| = \|!![1, 0; 0, ε]\|$.
      have h_unitary : mat_norm (P * D * !![0, 0; 0, ε / (2 * (|K| + 1)) - ε]) = mat_norm !![0, 0; 0, ε / (2 * (|K| + 1)) - ε] ∧ mat_norm (P * D * !![1, 0; 0, ε]) = mat_norm !![1, 0; 0, ε] := by
        have h_unitary : (P * D)ᵀ * (P * D) = 1 := by
          exact?;
        exact ⟨ mat_norm_unitary_mul _ _ h_unitary, mat_norm_unitary_mul _ _ h_unitary ⟩;
      -- Substitute the values from h_unitary and the fact that |η - ε| ≤ ε.
      have h_norm : mat_norm !![0, 0; 0, ε / (2 * (|K| + 1)) - ε] ≤ ε ∧ mat_norm !![1, 0; 0, ε] = max 1 ε := by
        constructor;
        · -- The norm of the matrix !![0, 0; 0, ε / (2 * (|K| + 1)) - ε] is |ε / (2 * (|K| + 1)) - ε|.
          have h_norm : mat_norm !![0, 0; 0, ε / (2 * (|K| + 1)) - ε] = |ε / (2 * (|K| + 1)) - ε| := by
            convert mat_norm_diagonal_two 0 ( ε / ( 2 * ( |K| + 1 ) ) - ε ) using 1;
            norm_num;
          exact h_norm.symm ▸ abs_le.mpr ⟨ by nlinarith [ abs_nonneg K, mul_div_cancel₀ ε ( by positivity : ( 2 * ( |K| + 1 ) ) ≠ 0 ) ], by nlinarith [ abs_nonneg K, mul_div_cancel₀ ε ( by positivity : ( 2 * ( |K| + 1 ) ) ≠ 0 ) ] ⟩;
        · convert mat_norm_diagonal_two 1 ε using 1;
          norm_num [ abs_of_pos, hε ];
      cases max_cases 1 ε <;> nlinarith;
    · unfold is_QR; aesop;
      · unfold bad_R; ext i j; fin_cases i <;> fin_cases j <;> norm_num [ Matrix.mul_apply ] ; ring;
        ring;
      · simp_all +decide [ Matrix.mul_assoc, is_perm_matrix_unitary, is_sign_matrix_unitary ];
        simp_all +decide [ ← Matrix.mul_assoc, is_perm_matrix_unitary, is_sign_matrix_unitary ];
      · unfold is_upper_triangular bad_R; aesop;
        fin_cases i <;> fin_cases j <;> trivial;
    · unfold bad_R at a ; norm_num at a ; ring_nf at a ; aesop;
      linarith [ abs_nonneg K ];
    · -- By definition of $bad\_A$ and $bad\_R$, we know that $(bad\_A ε) * (bad\_R ε K)⁻¹$ has the required properties.
      have h_cond : Matrix.conditionNumber (bad_A ε * (bad_R ε K)⁻¹) = 2 * (|K| + 1) := by
        exact?;
      cases abs_cases K <;> linarith

lemma PMF_toMeasure_eq_one_of_support_subset {α : Type*} [MeasurableSpace α] (p : PMF α) (s : Set α) (h : p.support ⊆ s) :
  p.toMeasure s = 1 := by
    rw [ PMF.toMeasure ];
    -- Since the support of p is a subset of s, the measure of s is equal to the measure of the entire space, which is 1.
    have h_measure : (p.toOuterMeasure.toMeasure (by
    -- The Carathéodory measure is the infimum of the outer measures of sets containing the support. Since the support is a subset of itself, the outer measure of the support is one of the terms in the infimum. Therefore, the infimum can't be larger than the outer measure of the support.
    apply le_of_forall_le;
    intro c hc; intro s hs; aesop;) : Set α → ENNReal) Set.univ = 1 := by
      simp +decide [ PMF.toOuterMeasure_apply ]
    generalize_proofs at *;
    -- Since the support of p is a subset of s and the measure of the entire space is 1, the measure of s must be exactly 1.
    have h_measure_s : (p.toOuterMeasure.toMeasure ‹_›) s ≥ (p.toOuterMeasure.toMeasure ‹_›) (p.support) := by
      apply_rules [ MeasureTheory.measure_mono ];
    refine' le_antisymm _ _;
    · exact h_measure ▸ MeasureTheory.measure_mono ( Set.subset_univ _ );
    · aesop;
      refine' le_trans _ h_measure_s;
      rw [ ← h_measure, MeasureTheory.measure_congr ];
      exact?;
      rw [ MeasureTheory.ae_eq_set ] ; aesop;
      simp +decide [ PMF.toOuterMeasure_apply ]

open Matrix

lemma norm_inequality_SRHT (ε K : ℝ) (hε : 0 < ε) :
  let η := ε / (2 * (|K| + 1))
  let E_diag := !![0, 0; 0, η - ε]
  let SA_diag := !![1, 0; 0, ε]
  mat_norm E_diag ≤ ε * mat_norm SA_diag := by
    -- By definition of matrix norm, we know that for a diagonal matrix, the norm is the maximum absolute value of its diagonal entries.
    have h_norm_diag : ∀ (a b : ℝ), mat_norm !![a, 0; 0, b] = max |a| |b| := by
      exact?;
    aesop;
    -- Since $|ε / (2 * (|K| + 1)) - ε| = ε - ε / (2 * (|K| + 1))$ and $ε - ε / (2 * (|K| + 1)) \leq ε$, we have $|ε / (2 * (|K| + 1)) - ε| \leq ε$.
    have h_abs : |ε / (2 * (|K| + 1)) - ε| ≤ ε := by
      exact abs_le.mpr ⟨ by nlinarith [ abs_nonneg K, div_mul_cancel₀ ε ( by positivity : ( 2 * ( |K| + 1 ) ) ≠ 0 ) ], by nlinarith [ abs_nonneg K, div_mul_cancel₀ ε ( by positivity : ( 2 * ( |K| + 1 ) ) ≠ 0 ) ] ⟩;
    exact le_trans h_abs ( le_mul_of_one_le_right hε.le ( le_max_left _ _ ) )

theorem instability_of_sketch_and_precondition_probabilistic :
  ∀ (ε K : ℝ), 0 < ε →
    ∃ (A : Matrix (Fin 2) (Fin 2) ℝ),
      random_SRHT_1_2.toMeasure {S | is_unstable S A ε K} = 1 := by
  intro ε K hε
  use bad_A ε
  apply PMF_toMeasure_eq_one_of_support_subset
  rw [random_SRHT_1_2]
  rw [PMF.support_uniformOfFinset]
  intro S hS
  apply instability_for_all_SRHT ε K hε S hS
